FROM python:3.9-slim

WORKDIR /app

COPY requirements_api.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
